<?php

/**
 * @file
 * Provides integration between TaxJar and Drupal Commerce.
 */

/**
 * Implements hook_menu().
 */
function commerce_taxjar_menu() {
  $items = array();
  $items['admin/commerce/config/taxjar'] = array(
    'title' => 'TaxJar Configuration',
    'description' => 'Configure API settings for TaxJar integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_taxjar_admin_settings_form'),
    'access arguments' => array('administer taxjar'),
    'file' => 'includes/commerce_taxjar.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function commerce_taxjar_permission() {
  return array(
    'administer taxjar' => array(
      'title' => t('Administer Commerce TaxJar'),
      'description' => t('Allows users to configure Commerce TaxJar'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Instantiates the TaxJar PHP component.
 * @return bool|\TaxJar\Client
 */
function commerce_taxjar_api() {
  $settings = variable_get('commerce_taxjar_settings');
  if (!empty($settings['api_key'])) {
    $taxjar = TaxJar\Client::withApiKey($settings['api_key']);
    if (!empty($taxjar)) {
      return $taxjar;
    }
  }
  return FALSE;
}

/**
 * Returns an array of taxjar settings that should be saved.
 */
function commerce_taxjar_settings_fields() {
  return array(
    'api_key',
    'default_tax_category',
  );
}

/**
 * Fetch the available TaxJar tax categories.
 */
function commerce_taxjar_categories_list() {
  $categories = array();
  $taxjar = commerce_taxjar_api();
  if (!empty($taxjar)) {
    $taxjar_categories = $taxjar->categories();
    if (!empty($taxjar_categories->categories)) {
      foreach ($taxjar_categories->categories as $taxjar_category) {
        $tax_code = check_plain($taxjar_category->product_tax_code);
        $tax_name = check_plain($taxjar_category->name);
        $categories[$tax_code] = $tax_name;
      }
    }
  }
  return $categories;
}
